# Generated by Django 5.2.1 on 2025-05-30 23:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('titulo_academico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Silabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=20, unique=True)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('ciclo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('creditos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('horas_teoricas', models.IntegerField(default=0)),
                ('horas_practicas', models.IntegerField(default=0)),
                ('sumilla', models.TextField()),
                ('competencia_general', models.TextField()),
                ('competencias_especificas', models.TextField()),
                ('prerequisitos', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silabos.carrera')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silabos.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('parcial', 'Examen Parcial'), ('final', 'Examen Final'), ('practica', 'Práctica Calificada'), ('trabajo', 'Trabajo'), ('otros', 'Otros')], max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semana', models.IntegerField()),
                ('silabo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='silabos.silabo')),
            ],
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('basica', 'Básica'), ('complementaria', 'Complementaria')], max_length=20)),
                ('autor', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=300)),
                ('anio', models.IntegerField()),
                ('editorial', models.CharField(max_length=200)),
                ('silabo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliografia', to='silabos.silabo')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDidactica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('duracion_semanas', models.IntegerField()),
                ('competencias', models.TextField()),
                ('silabo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='silabos.silabo')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('subtemas', models.TextField()),
                ('semana', models.IntegerField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='silabos.unidaddidactica')),
            ],
        ),
    ]
